### ISSUE TITLE
chat room

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#11]
We can consider adding a chat room to the app. It's not hard to implementation a naive one but hard to make a good one. I don't know any library we can use to do this. Maybe we can try to create a room at [slack](https://slack.com/) and add a link to the room.

**Comment by yuchenhou** [comment]
This is all too nice and easy: https://athanasea.ryver.com

**Comment by alanyuchenhou** [comment]
@ylhou , what do you think of [rocket chat](https://rocket.chat/) ?
