### ISSUE TITLE
forum

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#12]
I'll try to find an existing forum platform we can use. "Plug and play" components are always the best. Same thing goes for #11 .

**Comment by yuchenhou** [comment]
I found a forum platform that works out of the box and created one for athanasea. It also support chat room. Check it out: https://athanasea.ryver.com

**Comment by alanyuchenhou** [comment]
in #14 @Taxidea-Jen mentioned " it is important that this site not be linked to any external sites". So we'll need to use a forum package and host it on our own domain.

**Comment by ylhou** [comment]
how about NodeBB ?  an open source forum software, based on nodejs . we can customize it, deploy on our cloud, then embed it into athanasea. take a look
http://athanasea.nodebb.com/
https://github.com/NodeBB/NodeBB

**Comment by ylhou** [comment]
https://github.com/NodeBB/NodeBB

**Comment by ylhou** [comment]
https://github.com/NodeBB/NodeBB

athanasea.nodebb.com

**Comment by alanyuchenhou** [comment]
I think NodeBB has very high quality, and we should consider using it. I think we should let @Taxidea-Jen decide whether we self-host or use their hosting service. I still prefer using their hosting service, because this save us time(and equivalently, money) in the long run - unlimited storage, scalability, free updates/upgrades... On the other hand, I can see the advantage of self hosting too: the forum can have our domain name, style, and integrated login.

**Comment by Taxidea-Jen** [comment]
I'm completely fine with whatever forum template you would like to use, but I would prefer it to be on our domain name, if possible.  If you think it's better to use the athanasea.nodebb.com, then that's fine, just so long as there is seemless transition between the two sites (must be fully customizeable so it can look just like the rest of the site).

**Comment by alanyuchenhou** [comment]
@ylhou , do you think [telescope](http://www.telescopeapp.org/) is a better option than nodebb?

**Comment by ylhou** [comment]
now we are using telescope login module

**Comment by ylhou** [comment]
![1](https://cloud.githubusercontent.com/assets/7435136/12523713/7b244228-c193-11e5-819e-294a635af409.png)
![2](https://cloud.githubusercontent.com/assets/7435136/12523720/8127ea80-c193-11e5-9c89-1321c0f4e2a9.png)
 a bit progress about forum .

**Comment by alanyuchenhou** [comment]
That looks nice! Can you push the code?

**Comment by Taxidea-Jen** [comment]
I just want to ask if this is going to look like a website or a mobile device app, because those screen shots all look like an app for a mobile device, and I'm intending this to be a website.

**Comment by alanyuchenhou** [comment]
Hi @Taxidea-Jen , our web app should work well and look great on most of devices and operating systems, as long as you use a modern web browser(e.g. chrome, firefox, etc). The app should look differently with optimized visual effect depending on the device you use. I deployed it to our testing server at http://athanasea.meteor.com/ Give it a try with whatever device/OS/browser combo you have!

**Comment by ylhou** [comment]
now the question is, if we build a website only,  like http://www.eldemore.com/index.php,  items become too small to click when displayed on mobile.  our  implementation make the site usable for different devices.
we will  beautify the UI further

**Comment by alanyuchenhou** [comment]
Our earlier attempt on highly integrated forum and athanasea core wasn't very successful. I think it's better to reduce the coupling of the forum and the core. For now we can leave this issue to backlog and concentrate on the core feature development. Eventually we should deploy 2 of them separately for easier maintenance, with shared css and user account for consistency.
