### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#14]
We should consider supporting google, facebook, twitter, weibo accounts authorization.

**Comment by Taxidea-Jen** [comment]
Actually, it is important that this site not be linked to any external sites or social media because of COPPA and also the privacy rules that will be in place.  Users will not be able to share personal information.

**Comment by alanyuchenhou** [comment]
Do you mean a user should not be allowed to login with their google/facebook account and has to create an account at athanasea?

**Comment by Taxidea-Jen** [comment]
Yes.  The user must have an independent account just like on Chicken Smoothie or Eldemore.

**Comment by Taxidea-Jen** [comment]
That's why the phpBB forum framework is commonly used for these sites, because it already has that type of system built in.

**Comment by alanyuchenhou** [comment]
I see. How is the current login we have on http://athanasea.meteor.com ?

**Comment by Taxidea-Jen** [comment]
I think that's fine, but I would still prefer to have the site be phpBB-based, since that works so well for all of the other adoptable games (and other virtual pet sites) that I've seen.

**Comment by Taxidea-Jen** [comment]
Also, any login will have to be COPPA compliant, so we will need to verify the user's age (as best as we can) and have a way for them to submit parental approval if they are under 13 years of age.  In case you're not familiar with COPPA: http://www.coppa.org
