### ISSUE TITLE
privacy and external service

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#15]
As we decided to exclude U13 user group, do we still have to exclude external services? For example, social media: this can be a very effective and affordable way of advertising - they can "like" our app or show off their pets on Facebook, and effectively advertise our app. Also, I think people are more willing to try it out if they are allowed to login in using their existing account with Google, Facebook, etc, although I haven't studied related statistics.

**Comment by Taxidea-Jen** [comment]
I would still prefer it to be separate.  I understand the potential benefits of allowing users to link with social media, but I would rather the community be a safe place where users cannot be identified in real life.

**Comment by alanyuchenhou** [comment]
No problem. Then no social media.
