### ISSUE TITLE
deploying

### ISSUE THREAD

**Issue by ylhou** [yuchenhou/athanasea#17]
I have problems in uploading files to meteor.com.  so i will learn to deploy on our google cloud

**Comment by alanyuchenhou** [comment]
I deployed it to our testing server using Meteor CLI, but the deployment was very slow. Regarding deployment tools, I've heard of heroku. Ideally, we should setup a continuous delivery tool: every time anyone pushes new changes to our repo, the tool should build it, test it, and deploy(if all tests have passed) it automatically. Is this related to #8 ?

**Comment by alanyuchenhou** [comment]
I've set up heroku. Automatic deploys from master are enabled. Every push to master will deploy a new version of this app. Deploys happen automatically. Once we have #8 done, I'll change heroku to wait for CI to pass before deploy.
