### ISSUE TITLE
start user interface

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#19]
Let's do these 2 views first (from the user perspective):
1. when I click the "sea" button, I should see the list of species
2. when I click the "rescue center" button, I should see the list of animals I have

**Comment by ylhou** [comment]
this drag&drop board can be a general template as you said. I will try to copy one

**Comment by Taxidea-Jen** [comment]
I figure this is as good a time as any to share with you the mockups I made for what I would like the site to ideally look like.  I understand your concerns about website only vs. mobile-friendly, and I hope that it can still be mobile-friendly (I understand some modifications may need to be made).  I am/was hoping for a largely image-based navigation system for the site, which I know can be accomplished using Java and probably other languages.  These mockups are very rough and in no way dictate what the final site has to look like, but this is the direction I am ideally wanting it to go. http://s848.photobucket.com/user/taxideasims/library/Athanasea

**Comment by yuchenhou** [comment]
The mock-ups look cool, but very abstract, and rough too. I think modern UIs are usually minimalistic and mobile friendly. Although I don't use mobile devices very much, I do believe that's the case for most users nowadays, especially in online gaming:
![image](https://cloud.githubusercontent.com/assets/8304443/12534984/a797a19a-c226-11e5-9d68-96519371605a.png)
So I highly recommend we design the user interface to be mobile friendly, which means we might need to trade off some fancy visual effect.

**Comment by Taxidea-Jen** [comment]
While I agree that the interface should be mobile-friendly, I would rather have a mobile site version of the site and keep the website version visually stimulating than make the website version mobile-friendly.  Hopefully that makes sense.  I believe that Chicken Smoothie has done this, if you have the ability to look at the site from both a desktop and a mobile device.
