### ISSUE TITLE
cloud platform selection

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#2]
There are 2 platforms we can consider:
google: https://cloud.google.com/
amazon: https://aws.amazon.com/
I'm more inclined to google as its service is simpler and cheaper.

**Comment by Taxidea-Jen** [comment]
What would the cloud be used for?

**Comment by alanyuchenhou** [comment]
As a less technical answer, a cloud platform can provide many types of services our website needs. We can get these services ourselves, but a company like google can do the same thing costing only a fraction amount money in no time. That's why we should considering using a cloud platform.

For a little more technical answer, I found a good introduction here: https://cloud.google.com/solutions/websites/

**Comment by Taxidea-Jen** [comment]
Okay.  I think that having a cloud platform would be helpful, but I want to wait to invest in it until the site is at least partially developed and we can better assess how the cloud would be beneficial/integrated into the site.

**Comment by alanyuchenhou** [comment]
I see. That's a good point. We don't need to worry about this for now.
