### ISSUE TITLE
deleting species breaks rescue center

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#22]
### how to reproduce the problem
1. create a species
2. rescue a few animals from that species
3. delete the species
4. go to rescue center
### expected result

rescue center show other remaining animals (animals from that species are deleted)
### actual result

rescue center shows "loading", without loading anything
### console output

Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot read property 'subspp' of undefined
    at Document.Animals.helpers.spInfo (Animals.js:67)
    at lookup.js:207
    at Object.Spacebars.dot (spacebars-runtime.js:195)
    at null._render (template.Animal.js:26)
    at doRender (view.js:351)
    at view.js:199
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at view.js:197
    at Object.Blaze._withCurrentView (view.js:538)
    at viewAutorun (view.js:196)

**Comment by alanyuchenhou** [comment]
### reason

The 2 collections: spp and animals should have cascading delete and update, but mongoDB doesn't provide this.

### possible solution

Use [collection hooks](https://atmospherejs.com/matb33/collection-hooks)

**Comment by alanyuchenhou** [comment]
@lordofire can you fix this bug before working on #28 ?

**Comment by lordofire** [comment]
sure, let me take a look
