### ISSUE TITLE
Hosting service

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#3]
During the development, even if we don't use cloud hosting we still need some hosting, in order to run the app for testing and evaluation. Can we get free hosting from Vet school IT department?

**Comment by Taxidea-Jen** [comment]
I don't think so.  But I think Google had hosting options when I registered the domain.  I can check with them.

**Comment by Taxidea-Jen** [comment]
It looks like Google partners with these hosting sites: Blogger, SquareSpace, Wix, Shopify, and Weebly.  Hopefully one of those will work.

**Comment by alanyuchenhou** [comment]
Got it. Probably we can compare their offers(e.g. pricing) when we are ready to launch. For now - as I just realized - we can simply use free hosting from [Meteor](http://meteorpedia.com/read/Category:Meteor.Com). Everything is better when it's free.

**Comment by alanyuchenhou** [comment]
I was notified the hosting from Meteor is going to end permanently. We can move the site to the hosting from Heroku and MongoLab. The details about the end of hosting service is in this [thread](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308).

**Comment by alanyuchenhou** [comment]
I've moved the app to the new site at https://athanasea.herokuapp.com
The old site at athanasea.meteor.com is abandoned.
