### ISSUE TITLE
Solution stack

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#4]
Previously, we discussed using node.js, angular.js and express.js. But now I think instead of assembling these complex and separate frameworks together, we should use a full-stack framework like meteor. It looks like very powerful and also very easy to use. I suggest we use meteor. Can you take a look?

**Comment by ylhou** [comment]
同意并赞叹。meteor提供的机制可能很有前景

发自我的 iPhone

**Comment by alanyuchenhou** [comment]
Cool. Let's do that.

**Comment by alanyuchenhou** [comment]
meteor provides 3 front-end framework choices: blaze, angular and react. Let's use react as it appears to be the most popular and advanced one. Do you have any preference?

**Comment by alanyuchenhou** [comment]
User account components have only blaze implementation(there is no react implementation). But meteor provides a react wrapper for it so it's probably not a big deal.

**Comment by alanyuchenhou** [comment]
I tried it out: it's not hard to add user account using this wrapper. So let's just stay with react.

**Comment by alanyuchenhou** [comment]
Is it OK for us to use our current solution, meteor? It is way more superior than theirs - our technology, performance and user experience should be years ahead of them too. If you can take a quick look at the [features meteor provides](https://www.meteor.com/why-meteor/features), in just 1 minute, you can see what I'm talking about.

**Comment by Taxidea-Jen** [comment]
You can use whatever platform you like as long as you can integrate a phpBB-like forum into the site.  If there is a way to use meteor as a platform but also have a phpBB forum, that would be ideal.

**Comment by alanyuchenhou** [comment]
It's hard, but not impossible. However, as we don't need to comply with COPPA anymore, can we reconsider the solution I came up with in #12 ?

**Comment by Taxidea-Jen** [comment]
I don't know how to access the site in #12.  It takes me to a log in page, but I don't have a log in for the site.

**Comment by alanyuchenhou** [comment]
You need to have a ryver account to login. It has very high quality forum and chat and the hosting is also free. It's really a steal.

**Comment by Taxidea-Jen** [comment]
Maybe I'm missing something simple, but I can't seem to create an account.  The athanasea.ryver.com is already taken, and I don't know how to create a log in for that group.
