### ISSUE TITLE
meteor tutorial

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#5]
We should go over the turorial to learn how to build web app using meteor:
https://www.meteor.com/tutorials/react/creating-an-app

**Comment by Taxidea-Jen** [comment]
Wow!  Sounds good.  Is there anything you need from me right now?  I'm not sure what I can do at this point to help move things along.

**Comment by alanyuchenhou** [comment]
No. At this point, just be patient. We'll build a primitive demo app quickly and then it'll gradually morph into the goal app, during which you'll continuously provide directions and feedback.

**Comment by Taxidea-Jen** [comment]
Okay.  That's fine with me.  :)
