### ISSUE TITLE
app template

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#6]
Let's get the primitive app online. As you have already started working on it following the tutorial I'll just leave this to you.

**Comment by alanyuchenhou** [comment]
meteor provides 4 template apps: leaderboard, todo, clock, local market. After we finish the tutorial, we should take a look at them and identify their components our app also needs.

**Comment by yuchenhou** [comment]
Can you check out the 4 app templates meteor provides and pick one as our starting point? Then we can have some well constructed code base to build upon.

**Comment by alanyuchenhou** [comment]
I've been looking at template candidates and I just found a good match: [wekan](https://wekan.io/). Its features can be mapped to ours:
add tasks -> add animals
tasks' labels -> animals' species
tasks change stages -> animals grow
assignees get tasks -> adopters get animals

@ylhou what do you think?

**Comment by alanyuchenhou** [comment]
If we use telescope as our template instead of one of our package, how do we pull in telescope's upgrades?

**Comment by ylhou** [comment]
by adding or replacing template content and style, we can separate own code with in-package code 
refer to https://telescope.readme.io/docs
use custom_ prefix to mark template name

**Comment by alanyuchenhou** [comment]
I see. That'll be great!
