### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#7]
I'm trying to figure out how to do unit testing and acceptance testing. The [meter guide](http://guide.meteor.com/) will have more information in 1.3 release in a few weeks.

**Comment by ylhou** [comment]
travis-ci may provide solutions of testing

**Comment by alanyuchenhou** [comment]
Meteor 1.3 was released yesterday and I upgraded the platform to 1.3. The meter guide just added a lot of information about testing: unit testing, integration testing, acceptance testing and continuous integration. I'll be working on these.
