### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/athanasea#9]
Hola! @yuchenhou has created a [ZenHub](http://www.zenhub.io) account for the **yuchenhou** organization. ZenHub is the leading team collaboration and project management solution built for GitHub.

---
#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.
#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:
- Real-time, customizable task boards for GitHub issues;
- Burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- “+1” button for GitHub issues and comments;
- Drag-and-drop file sharing;
- Time-saving shortcuts like a quick repo switcher.
### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @yuchenhou._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by alanyuchenhou** [comment]
@ylhou We are asked to log our work hours, let's use Zenhub as our project manager.

**Comment by alanyuchenhou** [comment]
Let's assume 1 story point = 1 hour.

**Comment by ylhou** [comment]
add ZenHub plugin

**Comment by alanyuchenhou** [comment]
@ylhou @Taxidea-Jen ,
In order to improve the transparency of the project's progress, and a smooth communication and collaboration, we can use the task boards and burndown chart to keep track of issues(tasks) as they go through the pipeline: every task starts in "backlog"; the task flows into "to do" when it's scheduled for current milestone(with milestone, estimate specified); then it flows in "in progress" when someone starts to work on it(with assignee specified); then it flows in "done" when the assignee considers it done; then it flows in "closed" when a reviewer considers it "really done". Ideally, the assignee and the reviewer should be volunteered, but different persons. Any thoughts?

**Comment by Taxidea-Jen** [comment]
Most of that was gibberish to me, so if that's what you think is best, then go for it.

**Comment by alanyuchenhou** [comment]
@Taxidea-Jen  sorry about the confusion: for you, it just means you can view our progress at [the task board](https://github.com/yuchenhou/athanasea/issues/9#boards?repos=48735984).

**Comment by Taxidea-Jen** [comment]
Not a problem.  The link you made doesn't go anywhere, but I'm sure I can find the task board if you point me in the right direction.

**Comment by alanyuchenhou** [comment]
Sure. Can you see these 2 screenshots I attached?
![board](https://cloud.githubusercontent.com/assets/8304443/12314933/4b17ea3c-ba2a-11e5-8930-d432052551f0.png)
![burndown](https://cloud.githubusercontent.com/assets/8304443/12314934/4b195d54-ba2a-11e5-8fd2-245eb3bd77eb.png)

**Comment by Taxidea-Jen** [comment]
Yes.  Do I need to find ZipHub in order to view those pages?

**Comment by Taxidea-Jen** [comment]
ZenHub, that's what I meant.

**Comment by Taxidea-Jen** [comment]
One hiccup is that I don't use Google Chrome.  I use Safari or Firefox for my web browser.

**Comment by alanyuchenhou** [comment]
It should work with firefox. Can you give it a try?
